medicamentos = [
    "LORATADINA ILAB",
    "IBUPROFENO ILAB 600",
    "DICLONEX 50",
    "IBUPROFENO ILAB SUSPENSION",
    "KROLTONHEXINA ADULTOS",
    "TAREMIS",
    "AMITRIPTILINA LUAR",
    "CEFUROX",
    "CREMA DE BISMUTO ILAB",
    "INDUZEPAM",
    "IBULGIA 2%",
    "LOPERAMIDA ILAB",
    "IBUZIDINE",
    "OMEPRAZOL NEXO",
    "BROMHEXINA ILAB ELIXIR",
    "DICLONEX 100 AP",
    "MONIZOL",
    "CARVIPAW",
    "TAREMIS",
    "AZITROMICINA NEXO",
    "NEXOCARDIL",
    "FLUCONAZOL ILAB",
    "EUROFER",
    "AZITROMICINA NEXO",
    "TAREMIS",
    "QUIACORT",
    "NEXOTENSIL 5",
    "KERAMIX",
    "AMLODIPINA ILAB",
    "DICLONEX 75",
    "NEXOCARDIL",
    "CLORATEN",
    "IBUMEJORAL 400",
    "AMOXICILINA FECOFAR",
    "PRINOX 0.25 MG",
    "PARACETAMOL FECOFAR",
    "ALPRIM",
    "ATENOLOL VENT-3",
    "OMEPRAZOL NEXO",
    "AMLODIPINA ILAB",
    "CLARITROMICINA NEXO",
    "NEXOCARDIL",
    "RETEP",
    "FADALEX",
    "CLORATEN",
    "ATEL",
    "FORTUM",
    "PANAPROST",
    "NEXOTENSIL 10",
    "AIRCOSALM",
    "DOTALSEC",
    "IBUMEJORAL 400 RAPIDA ACCION",
    "CLARITROMICINA NEXO",
    "NEXOFLOXACIN 500",
    "HANEDA",
    "OMEPRAZOL ILAB",
    "ATIGLAUC",
    "CLORATEN",
    "DEXITIS",
    "BACTISONA CREMA",
    "FENDIPRAZOL",
    "CARVIPAW",
    "PANTOSEPTO",
    "ALPRIM",
    "NEXOSTATIN",
    "BIOXILINA DUO",
    "BECEDE 0.5",
    "NICOTIBINA",
    "BRONQUILAIR NASAL",
    "BIOXILINA PLUS DUO",
    "LOPERAMIDA CEVALLOS",
    "ALPRIM",
    "DIAZEPAM LEPRET",
    "CLARITROMICINA NEXO",
    "LORATADINA CEVALLOS",
    "LOSARTAN NEXO",
    "CLARITROMICINA NEXO",
    "IBUSOL PEDIATRICO",
    "CALMATRON",
    "QUEXEL SR 500",
    "ENALAPRIL 10 MG",
    "NORVIKEN 50 VENT-3",
    "BIPERIDENO CEVALLOS",
    "TENARON",
    "SUPRAFOL",
    "ISOSORBIDE 5 MONONITRATO TECHSPHERE",
    "LOSARTAN ILAB 50 MG",
    "NAPROXPHAR",
    "GENOCOLAN",
    "BILOINA",
    "BESUBIAL",
    "OMEFAR",
    "CLORPROMAZINA CEVALLOS",
    "MEDICORAN",
    "CEPOREXIN",
    "OMEPRAZOL VENT 3",
    "PROMETAZINA CEVALLOS",
    "PTA",
    "ALPRIM",
    "CLONAZEPAM LEPRET",
    "KETOROLAC 20 MG",
    "CEVICORT",
    "CLONAZEPAM CEVALLOS",
    "DICLOFENAC POTASICO CEVALLOS",
    "DIAZEPAM LEPRET",
    "KETOROLAC 10 MG SL",
    "BIOXILINA PLUS",
    "ALPRAZOLAM CEVALLOS",
    "GRENFUNG",
    "DAONIL",
    "PLENOBIOTIC DUO",
    "FLUNITRAZEPAM CEVALLOS",
    "GRENFUNG",
    "PRIMPERIL",
    "FLUOROGEL ORIGINAL",
    "IPRABRON",
    "OMEPRAZOL KILAB",
    "NEXOSTATIN",
    "REPLIDERM SPRAY",
    "ALPRAZOLAM CEVALLOS",
    "CREMA DE BISMUTO CEVALLOS",
    "ZOLDEM",
    "CLONAZEPAM CEVALLOS",
    "FADAMICINA",
    "FABOXIM",
    "CALMOFAR SL",
    "CEVICORT NC",
    "ALPRIM",
    "NEXOVITAL FOLICO",
    "TIBOCLIM",
    "METROCEV",
    "IBP PANTO",
    "KITACNE",
    "ERTA",
    "DUPRAC SL",
    "AEROTROP NEBU",
    "SALBUTRAL",
    "PAROXIN",
    "SOJAR FOLICO",
    "AMPICILINA + SULBACTAM NORGREEN",
    "AMLODIPINA TAURO",
    "NIVELAN-N",
    "SUPRAFOL",
    "NIVELAN-N",
    "CLONAZEPAM CEVALLOS",
    "KERAMIX RAPID",
    "CEFTRIAXONA NORGREEN",
    "ALLOPURINOL HEXAL 300",
    "SUPRAFOL",
    "CONGEX 24",
    "NISTAT",
    "FUROSEMIDA VENT-3",
    "PEDIASURE",
    "PTA",
    "AMPLIACTIL",
    "DUPRAC",
    "RISEDON 35",
    "NEXOVITAL FOLICO",
    "NORVIKEN 75 VENT-3",
    "FENOBARBITAL CEVALLOS",
    "DELTISONA RETARD",
    "PANTOCAS",
    "RACORVAL",
    "ISLOTIN 1000",
    "VENLAFAXINA CEVALLOS",
    "PTA",
    "KERAMIX",
    "TENARON",
    "PAROXIN",
    "DAONIL",
    "AFIDAT",
    "NORVIKEN 100 VENT-3",
    "OMEFAR",
    "PANTOSEPTO",
    "CLONAZEPAM CEVALLOS",
    "BUTAMOL",
    "FLUCODERM",
    "NISTAT",
    "VENLAFAXINA CEVALLOS",
    "BALFIBRO",
    "SUPRAFOL",
    "PROCINET NF",
    "LOTRIAL",
    "IBP PANTO",
    "FLUOXETINA CEVALLOS",
    "METFORMINA TECHSPHERE",
    "KARLIT 300",
    "BIPERIDENO CEVALLOS",
    "ALPRIM",
    "COVERFAX",
    "IZOTROP",
    "AKITROPIO",
    "TRIHEXIFENIDILO CEVALLOS",
    "AMITRIPTILINA CEVALLOS",
    "NEXOVITAL FOLICO",
    "DEXAMERAL 40",
    "RACORVAL",
    "DOXIBIOT",
    "IBUMEJORAL 600",
    "IZOTROP",
    "NAPROXPHAR",
    "BACLOFENO CEVALLOS",
    "OMEPRAZOL CEVALLOS",
    "PTA",
    "GADOPRIL",
    "FABOACID PANTO",
    "PONDERA 10",
    "ACTIMAX",
    "MINODIAB",
    "LAPRILENA",
    "FENERGAN",
    "NEUPRAM",
    "AFLIMET",
    "QUEXEL SR 850",
    "LOTRIAL",
    "ISONIAZIDA LAFEDAR",
    "ENATRAL 5 MG",
    "BISOFEC 2.5",
    "NORGESTREL PLUS",
    "TENCAS",
    "NEUPRAM"
]



# Lista de formas de presentación
presentaciones = [
    "10 mg comp.x 10",
    "600 mg comp.x 10",
    "50 mg comp.x 15",
    "susp.x 90 ml",
    "jbe.x 120 ml",
    "500 mg comp.x 10",
    "25 mg comp.rec.x 50",
    "750 mg f.a.x 1",
    "susp.x 90 ml",
    "susp.x 90 ml",
    "susp.x 90 ml",
    "0.25% sol.oral x 20 ml",
    "susp.x 120 ml",
    "comp.x 10",
    "400 mg comp.x 20",
    "20 mg caps.x 15",
    "80 mg/100 ml fco.x 120ml",
    "100 mg caps.x 15",
    "cr.x 30 g",
    "3.125 mg comp.x 30",
    "500 mg comp.x 20",
    "500 mg comp.x 3",
    "6.25 mg comp.x 28",
    "150 mg comp.x 2",
    "sol.x 20 ml",
    "200 mg/5 ml susp.x 15 ml",
    "500 mg ov.x 8",
    "cr.x 15 g",
    "5 mg comp.x 30",
    "10 mg comp.x 10",
    "5 mg comp.x 30",
    "75 mg comp.x 15",
    "12.5 mg comp.x 28",
    "6.25 mg comp.rec.x 28",
    "400 mg comp.x 20",
    "250 mg jbe.x 120 ml",
    "0.25 mg comp.x 30",
    "500 mg comp.x 20",
    "0.5 mg comp.rec.x 30",
    "50 mg comp.x 30",
    "20 mg caps.x 30",
    "10 mg comp.x 30",
    "500 mg comp.rec.x 8",
    "25 mg comp.x 28",
    "40 mg comp.x 50",
    "50 mg comp.x 20",
    "12.5 mg comp.rec.x 28",
    "50 mg comp.x 30",
    "1000 mg f.a.x 1",
    "2 mg comp.x 30",
    "10 mg comp.x 30",
    "fco.x 20 ml",
    "2 mg comp.x 20",
    "400 mg caps.blandas x 20",
    "125mg/5ml susp.x 60 ml",
    "500 mg comp.x 10",
    "comp.x 28",
    "20 mg caps.x 30",
    "0.5% gts.oft.x 10 ml",
    "25 mg comp.rec.x 28",
    "10 mg comp.x 10",
    "cr.x 30 g",
    "20 mg caps.x 28",
    "50 mg comp.x 30",
    "40 mg comp.gastr.x14",
    "1 mg comp.rec.x 30",
    "10 mg comp.rec.x 30",
    "750 mg/5 ml susp.x 70 ml",
    "0.5 mg comp.x 30",
    "300 mg comp.x 30",
    "spray nasal x 120 ds",
    "400 mg susp.x 70 ml",
    "2 mg comp.x 10",
    "0.5 mg comp.rec.x 60",
    "5 mg comp.x 30",
    "250mg/5ml susp.x 60 ml",
    "10 mg comp.x 10",
    "50 mg comp.rec.x 30",
    "500 mg comp.rec.x 16",
    "susp.x 100 ml",
    "2.5 mg comp.x 50",
    "500 mg comp.rec.AP x 30",
    "10 mg comp.x 30",
    "50 mg c ps.x 30",
    "2 mg comp.x 20",
    "15 mg comp.x 10",
    "1 mg comp.x 30",
    "20 mg comp.x 20",
    "comp.x 30",
    "250 mg comp.x 20",
    "jbe.x 120 ml",
    "jbe.x 60 ml",
    "50 mg comp.x 30",
    "20 mg caps.x 14",
    "25 mg comp.x 30",
    "80 mg caps.x 28",
    "500 mg susp.x 120 ml",
    "20 mg caps.x 14",
    "25 mg comp.rec.x 30",
    "0.5 mg comp.x 30",
    "2 mg comp.rec.x 30",
    "2 mg comp.x 30",
    "20 mg comp.x 10",
    "cr.x 15 g",
    "0.5 mg comp.x 30",
    "50 mg comp.x 30",
    "10 mg comp.x 30",
    "10 mg comp.subl.x 10",
    "500 mg comp.rec.x 16",
    "0.5 mg comp.x 30",
    "200 mg comp.x 10",
    "comp.x 30",
    "susp.x 70 ml",
    "1 mg comp.x 30",
    "2% cr.x 15 g",
    "comp.x 20",
    "0.24% tutti frutti x 60g",
    "sol.inhalatoria x 20 ml",
    "20 mg caps.x 14",
    "20 mg comp.rec.x 30",
    "1 g spray x 60 ml",
    "1 mg comp.x 30",
    "susp.x 90 ml",
    "10 mg comp.rec.x 30",
    "2 mg comp.x 30",
    "500 mg comp.x 16",
    "20 mg comp.rec.x 30",
    "10 mg comp.subl.x 10",
    "f.a.x 1 x 2 ml",
    "1 mg comp.rec.x 60",
    "1 mg comp.x 30",
    "2.5 mg comp.x 30",
    "tab.vag.x 12",
    "20 mg comp.x 14",
    "pomo x 30 g",
    "25 mg comp.rec.x 30",
    "10 mg comp.subl.x 10",
    "sol. p/nebul.x 20 ml",
    "sol.p/nebul.x 20 ml",
    "30 mg comp.rec.x 30",
    "1 mg comp.x 30",
    "1.5 g iny.f.a.x 1",
    "5 mg comp.x 30",
    "0.5 mg comp.x 30",
    "5 mg comp.x 30",
    "0.25 mg comp.x 60",
    "0.5 mg comp.x 60",
    "10 mg comp.subl.x 10",
    "1000 mg iny.f.a.x 1",
    "comp.x 30",
    "1 mg comp.x 60",
    "750 mg comp.ac.prol.x 10",
    "comp.vag.x 24",
    "comp. x 30",
    "Vainilla env.x 237 ml",
    "1 mg comp.x 30",
    "25 mg comp.x 30",
    "20 mg comp.x 10",
    "35 mg comp.rec.x 4",
    "5 mg comp.x 30",
    "75 mg c ps.x 30",
    "100 mg comp.x 50",
    "fco.a.x 1 x 2 ml+jeringa",
    "40 mg comp.x 15",
    "80 mg comp.rec.x 14",
    "1000 mg comp.rec.x 20",
    "50 mg comp.x 30",
    "0.5 mg comp.x 60",
    "20 mg comp.rec.x 10",
    "15 mg comp.x 20",
    "40 mg comp.rec.x 30",
    "comp.x 60",
    "25 mg comp.x 10",
    "100 mg c ps.x 30",
    "20 mg caps.x 28",
    "20 mg comp.gastr.x 30",
    "2 mg comp.x 60",
    "0.5% gts.p/nebul.x 10 ml",
    "150 mg comp.ran.x 2",
    "susp.oral x 60 ml",
    "75 mg comp.x 30",
    "75 mg caps.x 14",
    "5 mg comp.x 60",
    "200 mg comp.x 30",
    "2.5 mg comp.x 30",
    "40 mg comp.x 14",
    "20 mg comp.x 20",
    "500 mg comp.rec.x 30",
    "comp.x 20",
    "2 mg comp.x 60",
    "2 mg comp.rec.x 60",
    "10 mg comp.ran.x 14",
    "500 mg comp.x 3",
    "sol.x 20 ml",
    "5 mg comp.x 50",
    "75 mg comp.x 30",
    "1 mg comp.x 60",
    "40 mg comp.x 14",
    "160 mg comp.rec.x 14",
    "100 mg comp.x 20",
    "600 mg comp.x 50",
    "500 mg comp.x 6",
    "250 mg comp.x 50",
    "10 mg comp.x 50",
    "20 mg caps.x 28",
    "2 mg comp.x 30",
    "2.5 mg comp.ran.x 30",
    "20 mg comp.rec.x 30",
    "10 mg comp.rec.x 30",
    "70 mg comp.x 4",
    "5 mg comp.x 30",
    "5 mg comp.x 30",
    "comp.rec.x 30",
    "5 mg comp.x 30",
    "5 mg comp.rec.x 30",
    "850 mg comp.rec.AP x 30",
    "20 mg comp.x 28",
    "20 mg comp.x 28",
    "10 mg comp.x 30",
    "25 mg comp.x 28",
    "500 mg comp.x 20",
    "50 mg comp.x 30",
    "5% gel x 40 g",
    "5 mg comp.x 30",
    "50 mg comp.x 30",
    "500 mg comp.rec.x 16",
    "0.5 mg comp.x 60",
    "20 mg caps.x 28",
    "75 mg comp.x 30",
    "loc.x 30 ml",
    "50 mg comp.x 30",
    "500 mg comp.x 30",
    "10 mg comp.x 30",
    "100 mg comp.x 50",
    "20 mg comp.x 30",
    "20 mg comp.x 30",
    "5 mg comp.x 60",
    "comp.x 21",
    "10 mg comp.rec.x 30",
    "grag.x 21",
    "comp.x 21",
    "20 mg c ps.x 30",
    "75 mg comp.rapirtd.x 20",
    "400 mg comp.rec.x 20",
    "20 mg comp.ran.x 14",
    "1 mg comp.x 60",
    "150 mg comp.rec.x 1",
    "500 mg comp. x 30",
    "5 mg comp.x 60",
    "10 mg comp.rec.x 30",
    "37.5mg caps.lib.prol.x28",
    "50 mg comp.x 30",
    "50 mg comp.x 28",
    "1 mg comp.x 100",
    "600 mg comp.efer.x 20",
    "15 mg comp.x 15",
    "fco.x 10 ml",
    "850 mg comp.x 30",
    "750 mg comp.x 5",
    "50 mg comp.x 30",
    "5 mg comp.x 30",
    "5 mg comp.x 30",
    "1000 mg comp.rec.AP x 30",
    "gts.p/nebulizar x 20 ml",
    "5 mg comp.x 30",
    "5 mg comp.x 30",
    "300 mg comp.x 30",
    "5 mg comp.x 30",
    "2.5 mg comp.x 30",
    "comp.rec.x 21",
    "5 mg comp.x 30",
    "10 mg comp.x 30"
]

monodrogas = [
    "Paracetamol",
    "Ibuprofeno",
    "Aspirina",
    "Dipirona",
    "Codeína",
    "Tramadol",
    "Morfina",
    "Oxicodona",
    "Gabapentina",
    "Pregabalina",
    "Diclofenaco",
    "Naproxeno",
    "Ketoprofeno",
    "Indometacina",
    "Meloxicam",
    "Celecoxib",
    "Metformina",
    "Insulina",
    "Glimepirida",
    "Glibenclamida",
    "Pioglitazona",
    "Rosiglitazona",
    "Sitagliptina",
    "Vildagliptina",
    "Levothyroxine",
    "Liothyronine",
    "Estradiol",
    "Progesterona",
    "Testosterona",
    "Fluoxetina",
    "Sertralina",
    "Escitalopram",
    "Venlafaxina",
    "Olanzapina",
    "Risperidona",
    "Lorazepam",
    "Clonazepam",
    "Alprazolam",
    "Lisinopril",
    "Losartan",
    "Metoprolol",
    "Atenolol"
]

